# File: install-automation-cert.yml

steps:
- task: PowerShell@2
  displayName: Install Automation Cert
  inputs:
    targetType: inline
    script: >
      $kvSecretBytes = [System.Convert]::FromBase64String('$(AndroidAutomationRunner)')

      $certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection

      $certCollection.Import($kvSecretBytes, $null, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)


      $protectedCertificateBytes = $certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12)

      $pfxPath = '$(Build.SourcesDirectory)' + "\TestCert.pfx"

      [System.IO.File]::WriteAllBytes($pfxPath, $protectedCertificateBytes)


      Import-PfxCertificate -FilePath $pfxPath -CertStoreLocation Cert:\CurrentUser\My
